import { createFileRoute, Link } from "@tanstack/react-router";
import { breadcrumbSchema, schemaToString } from "@/lib/seo-schemas";

export const Route = createFileRoute("/blog/complete-guide-to-ai-pet-portraits")({
  head: () => ({
    meta: [
      {
        title:
          "The Complete Guide to AI Pet Portraits (2026) | Pawtoons",
      },
      {
        name: "description",
        content:
          "Everything you need to know about AI pet portraits in 2026: how they work, what they cost, how to choose a service, and how to get the best results from your photo.",
      },
      {
        property: "og:title",
        content: "The Complete Guide to AI Pet Portraits (2026)",
      },
      {
        property: "og:description",
        content:
          "How AI pet portraits work, what they cost, and how to get the best results. The definitive 2026 guide.",
      },
      {
        property: "og:url",
        content:
          "https://www.pawtoons.co/blog/complete-guide-to-ai-pet-portraits",
      },
      { property: "og:type", content: "article" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
    links: [
      {
        rel: "canonical",
        href: "https://www.pawtoons.co/blog/complete-guide-to-ai-pet-portraits",
      },
    ],
    scripts: [
      {
        type: "application/ld+json",
        children: schemaToString(
          breadcrumbSchema([
            { name: "Blog", url: "https://www.pawtoons.co/blog" },
            {
              name: "The Complete Guide to AI Pet Portraits",
              url: "https://www.pawtoons.co/blog/complete-guide-to-ai-pet-portraits",
            },
          ]),
        ),
      },
      {
        type: "application/ld+json",
        children: schemaToString({
          "@context": "https://schema.org",
          "@type": "Article",
          "headline": "The Complete Guide to AI Pet Portraits (2026)",
          "description":
            "Everything you need to know about AI pet portraits: how they work, what they cost, how to choose a service, and how to get the best results from your photo.",
          "author": {
            "@type": "Organization",
            "name": "Pawtoons",
          },
          "publisher": {
            "@type": "Organization",
            "name": "Pawtoons",
            "logo": {
              "@type": "ImageObject",
              "url": "https://www.pawtoons.co/assets/pawtoons-logo.png",
            },
          },
          "datePublished": "2026-06-12",
          "dateModified": "2026-06-12",
          "mainEntityOfPage": {
            "@type": "WebPage",
            "@id": "https://www.pawtoons.co/blog/complete-guide-to-ai-pet-portraits",
          },
        }),
      },
      {
        type: "application/ld+json",
        children: schemaToString({
          "@context": "https://schema.org",
          "@type": "FAQPage",
          "mainEntity": [
            {
              "@type": "Question",
              "name": "What is an AI pet portrait?",
              "acceptedAnswer": {
                "@type": "Answer",
                "text": "An AI pet portrait is a custom artwork of your pet generated by artificial intelligence from a single photo. You choose an art style and theme, and the AI produces a unique, high-resolution image in around 60 seconds.",
              },
            },
            {
              "@type": "Question",
              "name": "How much should I expect to pay for an AI pet portrait?",
              "acceptedAnswer": {
                "@type": "Answer",
                "text": "Prices vary widely. Budget AI portrait services like Pawtoons start from £1.99. Mid-range services charge £5-£25. Hand-painted alternatives typically cost £50-£400.",
              },
            },
            {
              "@type": "Question",
              "name": "What makes a good photo for an AI pet portrait?",
              "acceptedAnswer": {
                "@type": "Answer",
                "text": "A good photo is well-lit, in focus, and shows your pet's face clearly from a front-facing or three-quarter angle. Natural daylight works best. Avoid heavily shadowed or blurry photos.",
              },
            },
            {
              "@type": "Question",
              "name": "Can AI pet portraits be printed?",
              "acceptedAnswer": {
                "@type": "Answer",
                "text": "Yes, as long as the service provides a high-resolution file. Pawtoons portraits are delivered print-ready, suitable for framing at A4 size and larger.",
              },
            },
          ],
        }),
      },
    ],
  }),
  component: AIPetPortraitGuidePage,
});

function AIPetPortraitGuidePage() {
  return (
    <main className="min-h-screen">
      {/* Hero */}
      <section className="py-16 px-4 max-w-3xl mx-auto">
        <nav className="text-sm text-gray-500 mb-6" aria-label="Breadcrumb">
          <Link to="/">Home</Link>
          <span className="mx-2">/</span>
          <Link to="/blog/">Blog</Link>
          <span className="mx-2">/</span>
          <span>Complete Guide to AI Pet Portraits</span>
        </nav>
        <p className="text-sm text-gray-500 mb-2">Updated June 2026 · 9 min read</p>
        <h1 className="text-4xl md:text-5xl font-bold mb-4 leading-tight">
          The Complete Guide to AI Pet Portraits
        </h1>
        <p className="text-xl text-gray-600">
          Everything you need to know about turning your pet's photo into
          stunning AI artwork — how it works, what it costs, and how to get a
          result you'll actually want to frame.
        </p>
      </section>

      {/* Table of contents */}
      <section className="px-4 max-w-3xl mx-auto mb-12">
        <div className="bg-gray-50 rounded-2xl p-6">
          <h2 className="font-bold mb-3 text-sm uppercase tracking-wide text-gray-500">
            In this guide
          </h2>
          <ul className="space-y-2 text-sm">
            {[
              ["what-is-it", "What is an AI pet portrait?"],
              ["how-it-works", "How AI pet portrait generators work"],
              ["quality", "How good is the quality, really?"],
              ["cost", "How much do AI pet portraits cost?"],
              ["styles", "Choosing an art style"],
              ["themes", "Choosing a theme"],
              ["best-photo", "How to take the best photo for your portrait"],
              ["printing", "Printing and displaying your portrait"],
              ["choosing-service", "How to choose an AI pet portrait service"],
              ["faq", "Frequently asked questions"],
            ].map(([id, label]) => (
              <li key={id}>
                <a href={`#${id}`} className="text-blue-600 hover:underline">
                  {label}
                </a>
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* Section: What is it */}
      <section id="what-is-it" className="px-4 max-w-3xl mx-auto py-8">
        <h2 className="text-3xl font-bold mb-4">
          What Is an AI Pet Portrait?
        </h2>
        <p className="text-gray-700 mb-4">
          An AI pet portrait is a piece of custom artwork created entirely by
          artificial intelligence, using a photo of your pet as reference.
          Instead of commissioning a human artist — which can take weeks and
          cost hundreds of pounds — you upload a photo, choose a style and a
          creative theme, and an AI image generation model produces a unique
          portrait in seconds.
        </p>
        <p className="text-gray-700 mb-4">
          The output isn't a filter or a template. Modern AI portrait tools
          analyse your specific pet's features — their fur colour, face shape,
          ear position, expression — and generate an entirely new image that
          captures their likeness in the chosen artistic style.
        </p>
        <p className="text-gray-700">
          This category has grown rapidly since 2023, as AI image generation
          models became capable of producing genuinely high-quality, detailed
          artwork rather than the rough, distorted images that early AI tools
          were known for.
        </p>
      </section>

      {/* Section: How it works */}
      <section id="how-it-works" className="px-4 max-w-3xl mx-auto py-8 bg-gray-50">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-3xl font-bold mb-4">
            How AI Pet Portrait Generators Work
          </h2>
          <p className="text-gray-700 mb-4">
            At a high level, the process follows the same pattern across most
            services:
          </p>
          <ol className="space-y-4 mb-4">
            {[
              {
                title: "Upload a photo",
                body: "You provide one clear photo of your pet — usually a front-facing or three-quarter shot where their face is visible.",
              },
              {
                title: "Choose a style and theme",
                body: "Style determines the artistic medium (oil painting, watercolour, 3D animation). Theme determines the creative concept (royal, superhero, viking, and so on).",
              },
              {
                title: "AI generation",
                body: "The image generation model processes your photo alongside the style and theme prompts, producing a new image that combines your pet's likeness with the chosen aesthetic.",
              },
              {
                title: "Preview and refine",
                body: "Most quality services let you preview the result before paying, and offer regenerations if the first result isn't quite right.",
              },
              {
                title: "Download",
                body: "The final image is delivered as a high-resolution file, ready for printing or sharing.",
              },
            ].map((step, i) => (
              <li key={step.title} className="flex gap-4">
                <span className="w-8 h-8 bg-black text-white rounded-full flex items-center justify-center text-sm font-bold shrink-0">
                  {i + 1}
                </span>
                <div>
                  <h3 className="font-semibold mb-1">{step.title}</h3>
                  <p className="text-gray-600 text-sm">{step.body}</p>
                </div>
              </li>
            ))}
          </ol>
          <p className="text-gray-700">
            With Pawtoons, this entire pipeline takes about 60 seconds from
            upload to preview.
          </p>
        </div>
      </section>

      {/* Section: Quality */}
      <section id="quality" className="px-4 max-w-3xl mx-auto py-8">
        <h2 className="text-3xl font-bold mb-4">
          How Good Is the Quality, Really?
        </h2>
        <p className="text-gray-700 mb-4">
          This is the most common question people have, and understandably so
          — early AI image tools had a reputation for producing distorted,
          uncanny results.
        </p>
        <p className="text-gray-700 mb-4">
          That reputation is now largely outdated. Current-generation AI image
          models produce portraits with accurate proportions, coherent
          lighting, and genuinely impressive artistic detail. For pet
          portraits specifically — where the goal is often a fun,
          stylised result rather than photorealism — the quality is more than
          good enough for framing, printing, and gifting.
        </p>
        <p className="text-gray-700 mb-4">
          That said, quality varies between services. Things to look for:
        </p>
        <ul className="space-y-2 text-gray-700 mb-4 list-disc pl-5">
          <li>Resolution high enough for printing (at least suitable for A4)</li>
          <li>A preview step before you pay</li>
          <li>The ability to regenerate if the first result misses the mark</li>
          <li>Accurate likeness — does it actually look like your pet?</li>
        </ul>
        <p className="text-gray-700">
          Pawtoons addresses all of these: high-resolution output, free preview
          before checkout, and up to 3 free regenerations.
        </p>
      </section>

      {/* Section: Cost */}
      <section id="cost" className="px-4 max-w-3xl mx-auto py-8 bg-gray-50">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-3xl font-bold mb-4">
            How Much Do AI Pet Portraits Cost?
          </h2>
          <p className="text-gray-700 mb-4">
            Pricing in this category varies enormously, mostly based on
            generation volume, customisation options, and whether physical
            products are bundled in.
          </p>
          <div className="overflow-x-auto mb-4">
            <table className="w-full text-sm border-collapse">
              <thead>
                <tr className="bg-gray-100">
                  <th className="text-left p-3 font-semibold">Option</th>
                  <th className="text-left p-3 font-semibold">Typical Cost</th>
                  <th className="text-left p-3 font-semibold">Turnaround</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-t border-gray-200 bg-yellow-50">
                  <td className="p-3 font-semibold">Budget AI portrait (Pawtoons)</td>
                  <td className="p-3">From £1.99</td>
                  <td className="p-3">~60 seconds</td>
                </tr>
                <tr className="border-t border-gray-200">
                  <td className="p-3">Mid-range AI portrait apps</td>
                  <td className="p-3">£5–£25</td>
                  <td className="p-3">Minutes</td>
                </tr>
                <tr className="border-t border-gray-200">
                  <td className="p-3">Digital artist (commissioned)</td>
                  <td className="p-3">£25–£80</td>
                  <td className="p-3">3–7 days</td>
                </tr>
                <tr className="border-t border-gray-200">
                  <td className="p-3">Professional pet portrait artist</td>
                  <td className="p-3">£100–£400+</td>
                  <td className="p-3">2–6 weeks</td>
                </tr>
              </tbody>
            </table>
          </div>
          <p className="text-gray-700">
            For most everyday use cases — gifts, home decor, social sharing —
            budget AI portraits offer the best value by a wide margin, without
            a meaningful drop in visual quality compared to mid-range options.
          </p>
        </div>
      </section>

      {/* Section: Styles */}
      <section id="styles" className="px-4 max-w-3xl mx-auto py-8">
        <h2 className="text-3xl font-bold mb-4">Choosing an Art Style</h2>
        <p className="text-gray-700 mb-4">
          Most AI pet portrait services offer a handful of art styles. The
          three most common — and the three Pawtoons offers — are:
        </p>
        <div className="space-y-4">
          <div className="border-l-4 border-gray-200 pl-4">
            <h3 className="font-semibold mb-1">🎨 Oil Painting</h3>
            <p className="text-gray-600 text-sm">
              Rich colours, visible brushwork texture, classical composition.
              Best for a timeless, gallery-style look — particularly popular
              for memorial portraits and formal home decor.
            </p>
          </div>
          <div className="border-l-4 border-gray-200 pl-4">
            <h3 className="font-semibold mb-1">✨ Pixar / 3D</h3>
            <p className="text-gray-600 text-sm">
              Bold colours, exaggerated expressive features, cinematic
              lighting. Best for fun, shareable portraits — particularly
              popular for superhero and adventure themes.
            </p>
          </div>
          <div className="border-l-4 border-gray-200 pl-4">
            <h3 className="font-semibold mb-1">🌸 Watercolour</h3>
            <p className="text-gray-600 text-sm">
              Soft edges, delicate colour washes, artistic charm. Best for a
              gentle, elegant aesthetic — popular for gifts and nursery decor.
            </p>
          </div>
        </div>
        <p className="text-gray-700 mt-4">
          If you're unsure, Oil Painting is the safest choice for framing and
          formal display, while Pixar/3D tends to perform best for social media
          sharing.
        </p>
      </section>

      {/* Section: Themes */}
      <section id="themes" className="px-4 max-w-3xl mx-auto py-8 bg-gray-50">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-3xl font-bold mb-4">Choosing a Theme</h2>
          <p className="text-gray-700 mb-4">
            Theme is where most of the personality comes through. Popular
            options across the category include royal, superhero, fantasy
            (wizard, mermaid), historical (viking, pirate), and gentle/sentimental
            (angel, flower crown) — useful for memorial portraits.
          </p>
          <p className="text-gray-700 mb-4">
            A simple way to choose: think about your pet's personality, or the
            occasion for the portrait.
          </p>
          <ul className="space-y-2 text-gray-700 list-disc pl-5">
            <li><strong>For a gift:</strong> Superhero or Royal tend to land well with most recipients</li>
            <li><strong>For framing/home decor:</strong> Royal or Wizard in Oil Painting style</li>
            <li><strong>For a laugh:</strong> Mafia Boss, Pirate Captain, or Viking Warrior</li>
            <li><strong>For a memorial:</strong> Angel or Flower Crown in Watercolour</li>
            <li><strong>For social sharing:</strong> Astronaut or Superhero in Pixar/3D</li>
          </ul>
        </div>
      </section>

      {/* Section: Best photo */}
      <section id="best-photo" className="px-4 max-w-3xl mx-auto py-8">
        <h2 className="text-3xl font-bold mb-4">
          How to Take the Best Photo for Your Portrait
        </h2>
        <p className="text-gray-700 mb-4">
          The single biggest factor in portrait quality is the source photo.
          A few simple rules make a big difference:
        </p>
        <ul className="space-y-2 text-gray-700 list-disc pl-5 mb-4">
          <li><strong>Use natural light.</strong> Photos taken near a window or outdoors (not in direct harsh sun) produce the most accurate colours.</li>
          <li><strong>Get the face clearly visible.</strong> Front-facing or three-quarter angle works best. Avoid photos where the pet is looking away or partially obscured.</li>
          <li><strong>Avoid motion blur.</strong> A sharp, in-focus photo gives the AI more detail to work with.</li>
          <li><strong>Higher resolution is better.</strong> A modern smartphone photo is more than sufficient — avoid heavily compressed or very old, low-res images if possible.</li>
          <li><strong>Plain backgrounds help, but aren't essential.</strong> The AI focuses on your pet's features regardless of background.</li>
        </ul>
        <p className="text-gray-700">
          Even older or slightly imperfect photos — particularly useful for
          memorial portraits — will generally still produce a beautiful result,
          as long as the pet's face is reasonably clear.
        </p>
      </section>

      {/* Section: Printing */}
      <section id="printing" className="px-4 max-w-3xl mx-auto py-8 bg-gray-50">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-3xl font-bold mb-4">
            Printing and Displaying Your Portrait
          </h2>
          <p className="text-gray-700 mb-4">
            Once you have your high-resolution digital file, you have several
            options:
          </p>
          <ul className="space-y-2 text-gray-700 list-disc pl-5 mb-4">
            <li><strong>Print at home.</strong> Suitable for smaller sizes (A4) on a decent home printer with photo paper.</li>
            <li><strong>High street print shops.</strong> Boots, Snappy Snaps, and similar offer same-day printing at larger sizes, including canvas options.</li>
            <li><strong>Online print services.</strong> Order framed prints or canvases delivered to your door — typically 3–7 days.</li>
            <li><strong>Digital display.</strong> Phone wallpapers, digital photo frames, or simply sharing on social media.</li>
          </ul>
          <p className="text-gray-700">
            Because the file is yours to keep, you're not locked into any
            particular printing method — unlike services that only offer
            specific physical products.
          </p>
        </div>
      </section>

      {/* Section: Choosing a service */}
      <section id="choosing-service" className="px-4 max-w-3xl mx-auto py-8">
        <h2 className="text-3xl font-bold mb-4">
          How to Choose an AI Pet Portrait Service
        </h2>
        <p className="text-gray-700 mb-4">
          With dozens of services now available, here's what's actually worth
          checking before you pay:
        </p>
        <div className="space-y-3">
          {[
            { q: "Can you preview before paying?", a: "Avoid services that charge upfront with no preview — you have no way to know if the result looks like your pet." },
            { q: "What resolution is the final file?", a: "Make sure it's high enough for your intended use, especially if you plan to print." },
            { q: "How many regenerations are included?", a: "AI generation has some randomness — having at least one free regeneration is valuable." },
            { q: "How long does it actually take?", a: "Some services queue requests and take hours. Instant generation (under a minute) is now achievable and worth prioritising." },
            { q: "What's the real price, including any add-ons?", a: "Some services advertise a low headline price but add charges for higher resolution or extra styles." },
          ].map(({ q, a }) => (
            <div key={q} className="bg-gray-50 p-4 rounded-xl">
              <h3 className="font-semibold mb-1 text-sm">{q}</h3>
              <p className="text-gray-600 text-sm">{a}</p>
            </div>
          ))}
        </div>
        <div className="mt-8 bg-black text-white rounded-2xl p-6 text-center">
          <h3 className="text-xl font-bold mb-2">
            Pawtoons checks every box
          </h3>
          <p className="text-gray-300 text-sm mb-4">
            Free preview, high-resolution download, up to 3 free regenerations,
            generated in 60 seconds, from £1.99.
          </p>
          <Link
            to="/upload"
            className="inline-block bg-white text-black px-6 py-3 rounded-full font-semibold hover:bg-gray-100 transition"
          >
            Try Pawtoons Free →
          </Link>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="px-4 max-w-3xl mx-auto py-8 bg-gray-50">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-8">
            Frequently Asked Questions
          </h2>
          <div className="space-y-4">
            {[
              {
                q: "What is an AI pet portrait?",
                a: "An AI pet portrait is a custom artwork of your pet generated by artificial intelligence from a single photo. You choose an art style and theme, and the AI produces a unique, high-resolution image — typically in under a minute.",
              },
              {
                q: "How much should I expect to pay?",
                a: "Budget services like Pawtoons start from £1.99. Mid-range AI portrait apps charge £5–£25. Hand-painted alternatives typically run £50–£400.",
              },
              {
                q: "What makes a good photo for an AI pet portrait?",
                a: "Well-lit, in-focus photos with your pet's face clearly visible work best. Natural daylight is ideal. Front-facing or three-quarter angles give the most accurate results.",
              },
              {
                q: "Can AI pet portraits be printed?",
                a: "Yes, provided the service delivers a high-resolution file. Pawtoons portraits are print-ready and suitable for framing at A4 size and larger.",
              },
              {
                q: "Will the portrait actually look like my pet?",
                a: "Modern AI portrait generators are specifically designed to preserve your pet's individual features — fur colour, face shape, expression — while applying the chosen artistic style. The result should be clearly recognisable as your specific pet.",
              },
              {
                q: "Can I use an AI pet portrait as a memorial?",
                a: "Yes — this is one of the most common and meaningful uses. Even older photos of pets that have passed away can produce a beautiful memorial portrait, particularly in Watercolour or Angel-themed styles.",
              },
            ].map(({ q, a }) => (
              <details key={q} className="border border-gray-200 bg-white rounded-xl px-5 py-4">
                <summary className="font-semibold cursor-pointer">{q}</summary>
                <p className="text-gray-600 mt-2 text-sm">{a}</p>
              </details>
            ))}
          </div>
        </div>
      </section>

      {/* Internal links */}
      <section className="px-4 max-w-4xl mx-auto py-10 text-center">
        <h2 className="text-2xl font-bold mb-6">Explore Pawtoons</h2>
        <div className="flex flex-wrap justify-center gap-4">
          <Link to="/dog-portraits" className="bg-gray-50 border border-gray-200 px-5 py-3 rounded-xl hover:shadow transition">🐶 Dog Portraits</Link>
          <Link to="/cat-portraits" className="bg-gray-50 border border-gray-200 px-5 py-3 rounded-xl hover:shadow transition">🐱 Cat Portraits</Link>
          <Link to="/ai-pet-portraits" className="bg-gray-50 border border-gray-200 px-5 py-3 rounded-xl hover:shadow transition">✨ How AI Portraits Work</Link>
          <Link to="/pet-portrait-gifts" className="bg-gray-50 border border-gray-200 px-5 py-3 rounded-xl hover:shadow transition">🎁 Portrait Gifts</Link>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-16 px-4 text-center">
        <h2 className="text-3xl font-bold mb-4">
          Ready to See Your Pet as Art?
        </h2>
        <p className="text-gray-600 mb-6">
          Free preview · 60 seconds · From £1.99
        </p>
        <Link
          to="/upload"
          className="inline-block bg-black text-white px-10 py-4 rounded-full text-lg font-semibold hover:bg-gray-800 transition"
        >
          ✨ Create My Pet Portrait
        </Link>
      </section>
    </main>
  );
}
