/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuperheroPetPortraitsRouteImport } from './routes/superhero-pet-portraits'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as RoyalPetPortraitsRouteImport } from './routes/royal-pet-portraits'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PetPortraitGiftsRouteImport } from './routes/pet-portrait-gifts'
import { Route as PetMemorialPortraitsRouteImport } from './routes/pet-memorial-portraits'
import { Route as FunnyPetPortraitsRouteImport } from './routes/funny-pet-portraits'
import { Route as DogPortraitsRouteImport } from './routes/dog-portraits'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatPortraitsRouteImport } from './routes/cat-portraits'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiPetPortraitsRouteImport } from './routes/ai-pet-portraits'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogCompleteGuideToAiPetPortraitsRouteImport } from './routes/blog/complete-guide-to-ai-pet-portraits'
import { Route as BlogBestGiftsForDogLovers2026RouteImport } from './routes/blog/best-gifts-for-dog-lovers-2026'
import { Route as BlogBestGiftsForCatLovers2026RouteImport } from './routes/blog/best-gifts-for-cat-lovers-2026'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardPetsRouteImport } from './routes/_authenticated/dashboard.pets'
import { Route as AuthenticatedDashboardOrdersRouteImport } from './routes/_authenticated/dashboard.orders'
import { Route as AuthenticatedDashboardGenerationsRouteImport } from './routes/_authenticated/dashboard.generations'
import { Route as AuthenticatedDashboardFavoritesRouteImport } from './routes/_authenticated/dashboard.favorites'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperheroPetPortraitsRoute = SuperheroPetPortraitsRouteImport.update({
  id: '/superhero-pet-portraits',
  path: '/superhero-pet-portraits',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const RoyalPetPortraitsRoute = RoyalPetPortraitsRouteImport.update({
  id: '/royal-pet-portraits',
  path: '/royal-pet-portraits',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PetPortraitGiftsRoute = PetPortraitGiftsRouteImport.update({
  id: '/pet-portrait-gifts',
  path: '/pet-portrait-gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const PetMemorialPortraitsRoute = PetMemorialPortraitsRouteImport.update({
  id: '/pet-memorial-portraits',
  path: '/pet-memorial-portraits',
  getParentRoute: () => rootRouteImport,
} as any)
const FunnyPetPortraitsRoute = FunnyPetPortraitsRouteImport.update({
  id: '/funny-pet-portraits',
  path: '/funny-pet-portraits',
  getParentRoute: () => rootRouteImport,
} as any)
const DogPortraitsRoute = DogPortraitsRouteImport.update({
  id: '/dog-portraits',
  path: '/dog-portraits',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatPortraitsRoute = CatPortraitsRouteImport.update({
  id: '/cat-portraits',
  path: '/cat-portraits',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPetPortraitsRoute = AiPetPortraitsRouteImport.update({
  id: '/ai-pet-portraits',
  path: '/ai-pet-portraits',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCompleteGuideToAiPetPortraitsRoute =
  BlogCompleteGuideToAiPetPortraitsRouteImport.update({
    id: '/blog/complete-guide-to-ai-pet-portraits',
    path: '/blog/complete-guide-to-ai-pet-portraits',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBestGiftsForDogLovers2026Route =
  BlogBestGiftsForDogLovers2026RouteImport.update({
    id: '/blog/best-gifts-for-dog-lovers-2026',
    path: '/blog/best-gifts-for-dog-lovers-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBestGiftsForCatLovers2026Route =
  BlogBestGiftsForCatLovers2026RouteImport.update({
    id: '/blog/best-gifts-for-cat-lovers-2026',
    path: '/blog/best-gifts-for-cat-lovers-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPetsRoute =
  AuthenticatedDashboardPetsRouteImport.update({
    id: '/pets',
    path: '/pets',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOrdersRoute =
  AuthenticatedDashboardOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGenerationsRoute =
  AuthenticatedDashboardGenerationsRouteImport.update({
    id: '/generations',
    path: '/generations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFavoritesRoute =
  AuthenticatedDashboardFavoritesRouteImport.update({
    id: '/favorites',
    path: '/favorites',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-pet-portraits': typeof AiPetPortraitsRoute
  '/auth': typeof AuthRoute
  '/cat-portraits': typeof CatPortraitsRoute
  '/checkout': typeof CheckoutRoute
  '/dog-portraits': typeof DogPortraitsRoute
  '/funny-pet-portraits': typeof FunnyPetPortraitsRoute
  '/pet-memorial-portraits': typeof PetMemorialPortraitsRoute
  '/pet-portrait-gifts': typeof PetPortraitGiftsRoute
  '/privacy': typeof PrivacyRoute
  '/royal-pet-portraits': typeof RoyalPetPortraitsRoute
  '/success': typeof SuccessRoute
  '/superhero-pet-portraits': typeof SuperheroPetPortraitsRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/blog/best-gifts-for-cat-lovers-2026': typeof BlogBestGiftsForCatLovers2026Route
  '/blog/best-gifts-for-dog-lovers-2026': typeof BlogBestGiftsForDogLovers2026Route
  '/blog/complete-guide-to-ai-pet-portraits': typeof BlogCompleteGuideToAiPetPortraitsRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/favorites': typeof AuthenticatedDashboardFavoritesRoute
  '/dashboard/generations': typeof AuthenticatedDashboardGenerationsRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/pets': typeof AuthenticatedDashboardPetsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-pet-portraits': typeof AiPetPortraitsRoute
  '/auth': typeof AuthRoute
  '/cat-portraits': typeof CatPortraitsRoute
  '/checkout': typeof CheckoutRoute
  '/dog-portraits': typeof DogPortraitsRoute
  '/funny-pet-portraits': typeof FunnyPetPortraitsRoute
  '/pet-memorial-portraits': typeof PetMemorialPortraitsRoute
  '/pet-portrait-gifts': typeof PetPortraitGiftsRoute
  '/privacy': typeof PrivacyRoute
  '/royal-pet-portraits': typeof RoyalPetPortraitsRoute
  '/success': typeof SuccessRoute
  '/superhero-pet-portraits': typeof SuperheroPetPortraitsRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/best-gifts-for-cat-lovers-2026': typeof BlogBestGiftsForCatLovers2026Route
  '/blog/best-gifts-for-dog-lovers-2026': typeof BlogBestGiftsForDogLovers2026Route
  '/blog/complete-guide-to-ai-pet-portraits': typeof BlogCompleteGuideToAiPetPortraitsRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard/favorites': typeof AuthenticatedDashboardFavoritesRoute
  '/dashboard/generations': typeof AuthenticatedDashboardGenerationsRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/pets': typeof AuthenticatedDashboardPetsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/ai-pet-portraits': typeof AiPetPortraitsRoute
  '/auth': typeof AuthRoute
  '/cat-portraits': typeof CatPortraitsRoute
  '/checkout': typeof CheckoutRoute
  '/dog-portraits': typeof DogPortraitsRoute
  '/funny-pet-portraits': typeof FunnyPetPortraitsRoute
  '/pet-memorial-portraits': typeof PetMemorialPortraitsRoute
  '/pet-portrait-gifts': typeof PetPortraitGiftsRoute
  '/privacy': typeof PrivacyRoute
  '/royal-pet-portraits': typeof RoyalPetPortraitsRoute
  '/success': typeof SuccessRoute
  '/superhero-pet-portraits': typeof SuperheroPetPortraitsRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/blog/best-gifts-for-cat-lovers-2026': typeof BlogBestGiftsForCatLovers2026Route
  '/blog/best-gifts-for-dog-lovers-2026': typeof BlogBestGiftsForDogLovers2026Route
  '/blog/complete-guide-to-ai-pet-portraits': typeof BlogCompleteGuideToAiPetPortraitsRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/dashboard/favorites': typeof AuthenticatedDashboardFavoritesRoute
  '/_authenticated/dashboard/generations': typeof AuthenticatedDashboardGenerationsRoute
  '/_authenticated/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/_authenticated/dashboard/pets': typeof AuthenticatedDashboardPetsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-pet-portraits'
    | '/auth'
    | '/cat-portraits'
    | '/checkout'
    | '/dog-portraits'
    | '/funny-pet-portraits'
    | '/pet-memorial-portraits'
    | '/pet-portrait-gifts'
    | '/privacy'
    | '/royal-pet-portraits'
    | '/success'
    | '/superhero-pet-portraits'
    | '/terms'
    | '/upload'
    | '/admin'
    | '/dashboard'
    | '/blog/best-gifts-for-cat-lovers-2026'
    | '/blog/best-gifts-for-dog-lovers-2026'
    | '/blog/complete-guide-to-ai-pet-portraits'
    | '/blog/'
    | '/dashboard/favorites'
    | '/dashboard/generations'
    | '/dashboard/orders'
    | '/dashboard/pets'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-pet-portraits'
    | '/auth'
    | '/cat-portraits'
    | '/checkout'
    | '/dog-portraits'
    | '/funny-pet-portraits'
    | '/pet-memorial-portraits'
    | '/pet-portrait-gifts'
    | '/privacy'
    | '/royal-pet-portraits'
    | '/success'
    | '/superhero-pet-portraits'
    | '/terms'
    | '/upload'
    | '/admin'
    | '/blog/best-gifts-for-cat-lovers-2026'
    | '/blog/best-gifts-for-dog-lovers-2026'
    | '/blog/complete-guide-to-ai-pet-portraits'
    | '/blog'
    | '/dashboard/favorites'
    | '/dashboard/generations'
    | '/dashboard/orders'
    | '/dashboard/pets'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/ai-pet-portraits'
    | '/auth'
    | '/cat-portraits'
    | '/checkout'
    | '/dog-portraits'
    | '/funny-pet-portraits'
    | '/pet-memorial-portraits'
    | '/pet-portrait-gifts'
    | '/privacy'
    | '/royal-pet-portraits'
    | '/success'
    | '/superhero-pet-portraits'
    | '/terms'
    | '/upload'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/blog/best-gifts-for-cat-lovers-2026'
    | '/blog/best-gifts-for-dog-lovers-2026'
    | '/blog/complete-guide-to-ai-pet-portraits'
    | '/blog/'
    | '/_authenticated/dashboard/favorites'
    | '/_authenticated/dashboard/generations'
    | '/_authenticated/dashboard/orders'
    | '/_authenticated/dashboard/pets'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AiPetPortraitsRoute: typeof AiPetPortraitsRoute
  AuthRoute: typeof AuthRoute
  CatPortraitsRoute: typeof CatPortraitsRoute
  CheckoutRoute: typeof CheckoutRoute
  DogPortraitsRoute: typeof DogPortraitsRoute
  FunnyPetPortraitsRoute: typeof FunnyPetPortraitsRoute
  PetMemorialPortraitsRoute: typeof PetMemorialPortraitsRoute
  PetPortraitGiftsRoute: typeof PetPortraitGiftsRoute
  PrivacyRoute: typeof PrivacyRoute
  RoyalPetPortraitsRoute: typeof RoyalPetPortraitsRoute
  SuccessRoute: typeof SuccessRoute
  SuperheroPetPortraitsRoute: typeof SuperheroPetPortraitsRoute
  TermsRoute: typeof TermsRoute
  UploadRoute: typeof UploadRoute
  BlogBestGiftsForCatLovers2026Route: typeof BlogBestGiftsForCatLovers2026Route
  BlogBestGiftsForDogLovers2026Route: typeof BlogBestGiftsForDogLovers2026Route
  BlogCompleteGuideToAiPetPortraitsRoute: typeof BlogCompleteGuideToAiPetPortraitsRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superhero-pet-portraits': {
      id: '/superhero-pet-portraits'
      path: '/superhero-pet-portraits'
      fullPath: '/superhero-pet-portraits'
      preLoaderRoute: typeof SuperheroPetPortraitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/royal-pet-portraits': {
      id: '/royal-pet-portraits'
      path: '/royal-pet-portraits'
      fullPath: '/royal-pet-portraits'
      preLoaderRoute: typeof RoyalPetPortraitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pet-portrait-gifts': {
      id: '/pet-portrait-gifts'
      path: '/pet-portrait-gifts'
      fullPath: '/pet-portrait-gifts'
      preLoaderRoute: typeof PetPortraitGiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pet-memorial-portraits': {
      id: '/pet-memorial-portraits'
      path: '/pet-memorial-portraits'
      fullPath: '/pet-memorial-portraits'
      preLoaderRoute: typeof PetMemorialPortraitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funny-pet-portraits': {
      id: '/funny-pet-portraits'
      path: '/funny-pet-portraits'
      fullPath: '/funny-pet-portraits'
      preLoaderRoute: typeof FunnyPetPortraitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dog-portraits': {
      id: '/dog-portraits'
      path: '/dog-portraits'
      fullPath: '/dog-portraits'
      preLoaderRoute: typeof DogPortraitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cat-portraits': {
      id: '/cat-portraits'
      path: '/cat-portraits'
      fullPath: '/cat-portraits'
      preLoaderRoute: typeof CatPortraitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-pet-portraits': {
      id: '/ai-pet-portraits'
      path: '/ai-pet-portraits'
      fullPath: '/ai-pet-portraits'
      preLoaderRoute: typeof AiPetPortraitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/complete-guide-to-ai-pet-portraits': {
      id: '/blog/complete-guide-to-ai-pet-portraits'
      path: '/blog/complete-guide-to-ai-pet-portraits'
      fullPath: '/blog/complete-guide-to-ai-pet-portraits'
      preLoaderRoute: typeof BlogCompleteGuideToAiPetPortraitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/best-gifts-for-dog-lovers-2026': {
      id: '/blog/best-gifts-for-dog-lovers-2026'
      path: '/blog/best-gifts-for-dog-lovers-2026'
      fullPath: '/blog/best-gifts-for-dog-lovers-2026'
      preLoaderRoute: typeof BlogBestGiftsForDogLovers2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/best-gifts-for-cat-lovers-2026': {
      id: '/blog/best-gifts-for-cat-lovers-2026'
      path: '/blog/best-gifts-for-cat-lovers-2026'
      fullPath: '/blog/best-gifts-for-cat-lovers-2026'
      preLoaderRoute: typeof BlogBestGiftsForCatLovers2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/pets': {
      id: '/_authenticated/dashboard/pets'
      path: '/pets'
      fullPath: '/dashboard/pets'
      preLoaderRoute: typeof AuthenticatedDashboardPetsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/orders': {
      id: '/_authenticated/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/generations': {
      id: '/_authenticated/dashboard/generations'
      path: '/generations'
      fullPath: '/dashboard/generations'
      preLoaderRoute: typeof AuthenticatedDashboardGenerationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/favorites': {
      id: '/_authenticated/dashboard/favorites'
      path: '/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof AuthenticatedDashboardFavoritesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardFavoritesRoute: typeof AuthenticatedDashboardFavoritesRoute
  AuthenticatedDashboardGenerationsRoute: typeof AuthenticatedDashboardGenerationsRoute
  AuthenticatedDashboardOrdersRoute: typeof AuthenticatedDashboardOrdersRoute
  AuthenticatedDashboardPetsRoute: typeof AuthenticatedDashboardPetsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardFavoritesRoute: AuthenticatedDashboardFavoritesRoute,
    AuthenticatedDashboardGenerationsRoute:
      AuthenticatedDashboardGenerationsRoute,
    AuthenticatedDashboardOrdersRoute: AuthenticatedDashboardOrdersRoute,
    AuthenticatedDashboardPetsRoute: AuthenticatedDashboardPetsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AiPetPortraitsRoute: AiPetPortraitsRoute,
  AuthRoute: AuthRoute,
  CatPortraitsRoute: CatPortraitsRoute,
  CheckoutRoute: CheckoutRoute,
  DogPortraitsRoute: DogPortraitsRoute,
  FunnyPetPortraitsRoute: FunnyPetPortraitsRoute,
  PetMemorialPortraitsRoute: PetMemorialPortraitsRoute,
  PetPortraitGiftsRoute: PetPortraitGiftsRoute,
  PrivacyRoute: PrivacyRoute,
  RoyalPetPortraitsRoute: RoyalPetPortraitsRoute,
  SuccessRoute: SuccessRoute,
  SuperheroPetPortraitsRoute: SuperheroPetPortraitsRoute,
  TermsRoute: TermsRoute,
  UploadRoute: UploadRoute,
  BlogBestGiftsForCatLovers2026Route: BlogBestGiftsForCatLovers2026Route,
  BlogBestGiftsForDogLovers2026Route: BlogBestGiftsForDogLovers2026Route,
  BlogCompleteGuideToAiPetPortraitsRoute:
    BlogCompleteGuideToAiPetPortraitsRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
