// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token

    console.log('[auth-attacher] Session data:', {
      hasSession: !!data.session,
      hasToken: !!token,
      tokenPreview: token ? `${token.substring(0, 20)}...` : 'NO TOKEN',
      expiresAt: data.session?.expires_at,
      user: data.session?.user?.email
    })

    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
